import { SettingsPage } from '../components/settings-page'
import type { IntegrationSettings as IntegrationSettingsType } from '../types'
import {
  INTEGRATIONS_DEFAULT_SECTION,
  getIntegrationsSectionContent,
} from './section-registry.tsx'

const defaultIntegrationSettings: IntegrationSettingsType = {
  SMTPServer: '',
  SMTPPort: '',
  SMTPAccount: '',
  SMTPFrom: '',
  SMTPToken: '',
  SMTPSSLEnabled: false,
  SMTPForceAuthLogin: false,
  WorkerUrl: '',
  WorkerValidKey: '',
  WorkerAllowHttpImageRequestEnabled: false,
  ReconcileBalancePanelBaseURL: '',
  ReconcileBalancePanelToken: '',
  'model_deployment.ionet.api_key': '',
  'model_deployment.ionet.enabled': false,
  PayAddress: '',
  EpayId: '',
  EpayKey: '',
  Price: 7.3,
  MinTopUp: 1,
  CustomCallbackAddress: '',
  PayMethods: '',
  'payment_setting.amount_options': '',
  'payment_setting.amount_discount': '',
  StripeApiSecret: '',
  StripeWebhookSecret: '',
  StripePriceId: '',
  StripeUnitPrice: 8.0,
  StripeMinTopUp: 1,
  StripePromotionCodesEnabled: false,
  CreemApiKey: '',
  CreemWebhookSecret: '',
  CreemTestMode: false,
  CreemProducts: '[]',
  WaffoEnabled: false,
  WaffoApiKey: '',
  WaffoPrivateKey: '',
  WaffoPublicCert: '',
  WaffoSandboxPublicCert: '',
  WaffoSandboxApiKey: '',
  WaffoSandboxPrivateKey: '',
  WaffoSandbox: false,
  WaffoMerchantId: '',
  WaffoCurrency: 'USD',
  WaffoUnitPrice: 1,
  WaffoMinTopUp: 1,
  WaffoNotifyUrl: '',
  WaffoReturnUrl: '',
  WaffoPayMethods: '[]',
  WaffoAllowedGroups: '',
  WaffoPancakeEnabled: false,
  WaffoPancakeSandbox: false,
  WaffoPancakeMerchantID: '',
  WaffoPancakePrivateKey: '',
  WaffoPancakeWebhookPublicKey: '',
  WaffoPancakeWebhookTestKey: '',
  WaffoPancakeStoreID: '',
  WaffoPancakeProductID: '',
  WaffoPancakeReturnURL: '',
  WaffoPancakeCurrency: 'USD',
  WaffoPancakeUnitPrice: 1,
  WaffoPancakeMinTopUp: 1,
  WaffoPancakeAllowedGroups: '',
  WaffoPancakePayChannels: '[]',
  WaffoPancakeLogo: '',
  CryptomusEnabled: false,
  CryptomusMerchantID: '',
  CryptomusPaymentApiKey: '',
  CryptomusWebhookApiKey: '',
  CryptomusDefaultCurrency: 'USDT',
  CryptomusDefaultNetwork: 'TRX',
  CryptomusAllowedCurrencies: 'USDT,BTC,ETH,SOL,TRX',
  CryptomusUnitPrice: 1,
  CryptomusMinTopUp: 1,
  CryptomusReturnURL: '',
  CryptomusAllowedGroups: '',
  CryptomusPayChannels: '[]',
  CryptomusLogo: '',
  BepusdtEnabled: false,
  BepusdtBaseURL: '',
  BepusdtApiToken: '',
  BepusdtCurrencies: 'USDT',
  BepusdtLifetimeSec: 1200,
  BepusdtUnitPrice: 1,
  BepusdtMinTopUp: 1,
  BepusdtReturnURL: '',
  BepusdtAllowedGroups: '',
  BepusdtPayChannels: '[]',
  BepusdtLogo: '',
  SfpayEnabled: false,
  SfpayBaseURL: '',
  SfpayAppId: '',
  SfpayAppSecret: '',
  SfpayGroupCode: '',
  SfpayNotifyUrl: '',
  SfpayReturnUrl: '',
  SfpayUnitPrice: 7.3,
  SfpayMinTopUp: 1,
  SfpayMaxTopUp: 0,
  SfpayAllowedCallbackIPs: '',
  SfpayAlipayPayType: 'ZFBPAY',
  SfpayWechatEnabled: false,
  SfpayWechatPayType: '',
  SfpayAllowedGroups: '',
  SfpayPayChannels: '[]',
  SfpayLogo: '',
}

export function IntegrationSettings() {
  return (
    <SettingsPage
      routePath='/_authenticated/system-settings/integrations/$section'
      defaultSettings={defaultIntegrationSettings}
      defaultSection={INTEGRATIONS_DEFAULT_SECTION}
      getSectionContent={getIntegrationsSectionContent}
    />
  )
}
