import { SettingsPage } from '../components/settings-page'
import type { IntegrationSettings as IntegrationSettingsType } from '../types'
import {
  INTEGRATIONS_DEFAULT_SECTION,
  getIntegrationsSectionContent,
} from './section-registry.tsx'

const defaultIntegrationSettings: IntegrationSettingsType = {
  SMTPServer: '',
  SMTPPort: '',
  SMTPAccount: '',
  SMTPFrom: '',
  SMTPToken: '',
  SMTPSSLEnabled: false,
  SMTPForceAuthLogin: false,
  WorkerUrl: '',
  WorkerValidKey: '',
  WorkerAllowHttpImageRequestEnabled: false,
  ReconcileBalancePanelBaseURL: '',
  ReconcileBalancePanelToken: '',
  ChannelDisableThreshold: '',
  QuotaRemindThreshold: '',
  AutomaticDisableChannelEnabled: false,
  AutomaticEnableChannelEnabled: false,
  AutomaticDisableKeywords: '',
  AutomaticDisableStatusCodes: '401',
  AutomaticRetryStatusCodes:
    '100-199,300-399,401-407,409-499,500-503,505-523,525-599',
  'monitor_setting.auto_test_channel_enabled': false,
  'monitor_setting.auto_test_channel_minutes': 10,
  'channel_health_setting.enabled': false,
  'channel_health_setting.base_degrade_threshold': 5,
  'channel_health_setting.level_step_threshold': 5,
  'channel_health_setting.max_degrade_level': 10,
  'channel_health_setting.min_weight_factor': 0.05,
  'channel_health_setting.max_ttft_ms': 0,
  'channel_health_setting.latency_degrade_base': 5,
  'channel_health_setting.latency_degrade_step': 5,
  'channel_health_setting.count_latency_as_error': false,
  'channel_health_setting.disable_threshold': 0,
  'channel_health_setting.upgrade_threshold': 20,
  'channel_health_setting.degrade_probe_minutes': 10,
  'channel_health_setting.degrade_probe_count': 5,
  'channel_health_setting.count_429_as_error': true,
  'channel_health_setting.countable_status_codes': '',
  'channel_health_setting.notify_on_degrade': false,
  'channel_health_setting.notify_on_upgrade': false,
  'channel_health_setting.streak_window_sec': 600,
  'channel_health_setting.rebounce_protection_minutes': 0,
  'channel_health_setting.rebounce_protection_threshold': 3,
  'channel_health_setting.demote_cooldown_sec': 60,
  'channel_health_setting.recovery_strategy': 'probe',
  'channel_health_setting.recovery_probe_minutes': 30,
  'channel_health_setting.recovery_probe_model': '',
  'channel_health_setting.shadow_sample_rate': 0.001,
  'channel_health_setting.skip_channel_tags': '',
  'model_deployment.ionet.api_key': '',
  'model_deployment.ionet.enabled': false,
  PayAddress: '',
  EpayId: '',
  EpayKey: '',
  Price: 7.3,
  MinTopUp: 1,
  CustomCallbackAddress: '',
  PayMethods: '',
  'payment_setting.amount_options': '',
  'payment_setting.amount_discount': '',
  StripeApiSecret: '',
  StripeWebhookSecret: '',
  StripePriceId: '',
  StripeUnitPrice: 8.0,
  StripeMinTopUp: 1,
  StripePromotionCodesEnabled: false,
  CreemApiKey: '',
  CreemWebhookSecret: '',
  CreemTestMode: false,
  CreemProducts: '[]',
  WaffoEnabled: false,
  WaffoApiKey: '',
  WaffoPrivateKey: '',
  WaffoPublicCert: '',
  WaffoSandboxPublicCert: '',
  WaffoSandboxApiKey: '',
  WaffoSandboxPrivateKey: '',
  WaffoSandbox: false,
  WaffoMerchantId: '',
  WaffoCurrency: 'USD',
  WaffoUnitPrice: 1,
  WaffoMinTopUp: 1,
  WaffoNotifyUrl: '',
  WaffoReturnUrl: '',
  WaffoPayMethods: '[]',
  WaffoAllowedGroups: '',
  WaffoPancakeEnabled: false,
  WaffoPancakeSandbox: false,
  WaffoPancakeMerchantID: '',
  WaffoPancakePrivateKey: '',
  WaffoPancakeWebhookPublicKey: '',
  WaffoPancakeWebhookTestKey: '',
  WaffoPancakeStoreID: '',
  WaffoPancakeProductID: '',
  WaffoPancakeReturnURL: '',
  WaffoPancakeCurrency: 'USD',
  WaffoPancakeUnitPrice: 1,
  WaffoPancakeMinTopUp: 1,
  WaffoPancakeAllowedGroups: '',
  WaffoPancakePayChannels: '[]',
  WaffoPancakeLogo: '',
  CryptomusEnabled: false,
  CryptomusMerchantID: '',
  CryptomusPaymentApiKey: '',
  CryptomusWebhookApiKey: '',
  CryptomusDefaultCurrency: 'USDT',
  CryptomusDefaultNetwork: 'TRX',
  CryptomusAllowedCurrencies: 'USDT,BTC,ETH,SOL,TRX',
  CryptomusUnitPrice: 1,
  CryptomusMinTopUp: 1,
  CryptomusReturnURL: '',
  CryptomusAllowedGroups: '',
  CryptomusPayChannels: '[]',
  CryptomusLogo: '',
  SfpayEnabled: false,
  SfpayBaseURL: '',
  SfpayAppId: '',
  SfpayAppSecret: '',
  SfpayGroupCode: '',
  SfpayNotifyUrl: '',
  SfpayReturnUrl: '',
  SfpayUnitPrice: 7.3,
  SfpayMinTopUp: 1,
  SfpayMaxTopUp: 0,
  SfpayAllowedCallbackIPs: '',
  SfpayAlipayPayType: 'ZFBPAY',
  SfpayWechatEnabled: false,
  SfpayWechatPayType: '',
  SfpayAllowedGroups: '',
  SfpayPayChannels: '[]',
  SfpayLogo: '',
}

export function IntegrationSettings() {
  return (
    <SettingsPage
      routePath='/_authenticated/system-settings/integrations/$section'
      defaultSettings={defaultIntegrationSettings}
      defaultSection={INTEGRATIONS_DEFAULT_SECTION}
      getSectionContent={getIntegrationsSectionContent}
    />
  )
}
